name: Deploy Angular

on:
  workflow_dispatch:
  
jobs:
  deploy-angular:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v8
        with: 
          name: build-artifact
          path: artifact
          run_number: 15
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}

      - name: Display structure of downloaded files
        run: ls -R artifact
