name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * 3 * 0'

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Log time
        run: | 
          current_data_time=$(date)
          echo "Current date and time: $current_date_time"
